# 01 — Data Audit

## Objective
Perform an initial audit of the available NOVAres SecureHealth datasets to verify:

- dataset availability
- shapes and columns
- missing values
- duplicates
- key consistency across tables
- first business sanity checks

This notebook is the starting point for the analytical repository.

In [1]:
from pathlib import Path
import sys
import os

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("Notebook cwd:", Path.cwd())
print("data/raw exists:", (PROJECT_ROOT / "data" / "raw").exists())
print("Files in data/raw:", os.listdir(PROJECT_ROOT / "data" / "raw"))

PROJECT_ROOT: C:\Users\dolivares\Desktop\novares-securehealth
Notebook cwd: C:\Users\dolivares\Desktop\novares-securehealth\notebooks
data/raw exists: True
Files in data/raw: ['claims_corrected.csv', 'dataset_summary.csv', 'insured_members.csv', 'member_year_features_corrected.csv', 'policies.csv', 'prospect_survey_synthetic.csv', 'providers.csv', 'provider_month_features.csv']

In [2]:
import pandas as pd
import numpy as np

from src.config import RAW_DIR
from src.data.load_data import (
    load_insured_members,
    load_policies,
    load_providers,
    load_claims,
    load_member_year_features,
    load_provider_month_features,
    load_prospect_survey,
    load_dataset_summary,
)

In [3]:
# Load datasets
members = load_insured_members()
policies = load_policies()
providers = load_providers()
claims = load_claims()
member_year = load_member_year_features()
provider_month = load_provider_month_features()
prospects = load_prospect_survey()
dataset_summary = load_dataset_summary()

datasets = {
    "insured_members": members,
    "policies": policies,
    "providers": providers,
    "claims": claims,
    "member_year_features": member_year,
    "provider_month_features": provider_month,
    "prospect_survey": prospects,
    "dataset_summary": dataset_summary,
}

In [4]:
summary_rows = []
for name, df in datasets.items():
    summary_rows.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

pd.DataFrame(summary_rows).sort_values("dataset").reset_index(drop=True)

                   dataset   rows  columns
0                   claims  44144       36
1          dataset_summary      7        3
2          insured_members   4000       32
3     member_year_features   8000       37
4                 policies   4000       25
5          prospect_survey   7000       30
6  provider_month_features   4263       24
7                providers    180       17

In [5]:
# Columns by dataset
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)
    print(df.columns.tolist())
    print()

================================================================================
INSURED_MEMBERS
================================================================================
['member_id', 'policy_id', 'join_date', 'age', 'age_band', 'sex', 'region', 'city_tier', 'socioeconomic_band', 'employment_status', 'marital_status', 'dependents_n', 'family_complexity', 'smoker_flag', 'alcohol_risk_flag', 'physical_activity_level', 'bmi_group', 'chronic_condition_flag', 'chronic_condition_count', 'chronic_group', 'recurrent_medication_flag', 'prior_hospitalization_24m_flag', 'self_management_adherence', 'archetype', 'baseline_risk_score', 'utilization_propensity', 'acute_event_propensity', 'misuse_exposure_propensity', 'price_sensitivity', 'coverage_preference', 'network_preference', 'preferred_plan_type']

================================================================================
POLICIES
================================================================================
['policy_id', 'member_id', 'policy_start_date', 'policy_end_date', 'active_flag', 'plan_type', 'plan_tier', 'coverage_scope', 'provider_network_type', 'deductible_amount', 'copay_level', 'annual_coverage_limit', 'maternity_coverage_flag', 'pharmacy_coverage_flag', 'chronic_care_program_flag', 'premium_monthly', 'premium_annual', 'underwriting_load_factor', 'discount_factor', 'recommended_plan_flag', 'pricing_adequacy_ratio', 'renewal_flag', 'cancellation_flag', 'sales_channel', 'broker_id']

================================================================================
PROVIDERS
================================================================================
['provider_id', 'provider_name', 'provider_type', 'specialty_group', 'region', 'city_tier', 'network_status', 'provider_archetype', 'contract_type', 'base_cost_multiplier', 'diagnostic_intensity', 'admission_intensity', 'average_claim_expected', 'historical_volume_band', 'historical_suspicion_flag', 'provider_quality_proxy', 'fraud_exposure_score']

================================================================================
CLAIMS
================================================================================
['claim_id', 'member_id', 'policy_id', 'provider_id', 'claim_date', 'claim_year', 'claim_month', 'service_type', 'service_category', 'diagnosis_group', 'diagnosis_severity', 'procedure_code_group', 'procedure_complexity', 'emergency_flag', 'inpatient_flag', 'surgery_flag', 'pharmacy_flag', 'preventive_flag', 'chronic_related_flag', 'maternity_related_flag', 'claim_amount_billed', 'claim_amount_approved', 'claim_amount_rejected', 'out_of_pocket_estimated', 'claim_processing_days', 'approval_rate', 'duplicate_claim_flag', 'temporal_anomaly_flag', 'upcoding_suspected_flag', 'provider_inflation_flag', 'mismatch_dx_proc_flag', 'suspicious_claim_flag', 'fraud_pattern_type', 'member_archetype_snapshot', 'cost_expected_band', 'claim_outlier_score_latent']

================================================================================
MEMBER_YEAR_FEATURES
================================================================================
['member_id', 'year', 'archetype', 'age', 'plan_type', 'premium_annual', 'claims_count_total', 'claims_count_outpatient', 'claims_count_emergency', 'claims_count_inpatient', 'claims_count_pharmacy', 'providers_unique_n', 'specialties_unique_n', 'preventive_claims_n', 'chronic_claims_n', 'billed_total', 'approved_total', 'rejected_total', 'avg_claim_amount', 'max_claim_amount', 'p95_claim_amount', 'emergency_ratio', 'inpatient_ratio', 'preventive_ratio', 'chronic_ratio', 'duplicate_claims_n', 'suspicious_claims_n', 'suspicious_claim_ratio', 'provider_suspicious_exposure_n', 'acute_high_cost_event_flag', 'annual_cost_trend_vs_prev', 'loss_ratio_member', 'expected_cost_next_year', 'high_risk_flag', 'risk_tier', 'recommended_plan', 'pricing_gap']

================================================================================
PROVIDER_MONTH_FEATURES
================================================================================
['provider_id', 'year_month', 'claims_n', 'members_unique_n', 'billed_total', 'approved_total', 'avg_claim_amount', 'median_claim_amount', 'p95_claim_amount', 'emergency_claims_n', 'inpatient_claims_n', 'preventive_claims_n', 'duplicate_claims_n', 'suspicious_claims_n', 'dx_proc_mismatch_n', 'high_severity_share', 'suspicious_claim_ratio', 'provider_type', 'specialty_group', 'provider_archetype', 'cost_vs_peer_index', 'utilization_density_index', 'anomaly_score_provider', 'provider_alert_level']

================================================================================
PROSPECT_SURVEY
================================================================================
['prospect_id', 'age', 'age_band', 'sex', 'region', 'dependents_n', 'self_rated_health', 'chronic_condition_flag', 'chronic_condition_count', 'recurrent_medication_flag', 'visits_12m_band', 'er_visits_12m_band', 'hospitalization_24m_flag', 'smoker_flag', 'bmi_group', 'physical_activity_level', 'preventive_mindset', 'price_vs_coverage_preference', 'copay_tolerance', 'network_preference', 'maternity_interest_flag', 'pharmacy_need_flag', 'chronic_program_interest_flag', 'predicted_ground_truth_archetype', 'risk_tier', 'expected_utilization_band', 'recommended_plan', 'recommended_plan_tier', 'notes_driver_1', 'notes_driver_2']

================================================================================
DATASET_SUMMARY
================================================================================
['dataset', 'rows', 'columns']

In [6]:
# Preview first rows
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    display(df.head(3))

================================================================================
INSURED_MEMBERS

,member_id,policy_id,join_date,age,age_band,sex,region,city_tier,socioeconomic_band,employment_status,...,self_management_adherence,archetype,baseline_risk_score,utilization_propensity,acute_event_propensity,misuse_exposure_propensity,price_sensitivity,coverage_preference,network_preference,preferred_plan_type
0,MBR000001,POL000001,2022-09-24,47,45-54,M,San Pedro,Urban,Upper-Middle,Self-Employed,...,Low,Hyper-Utilizer / Misuse Risk,0.591,0.847,0.205,0.865,High,Balanced,Balanced,Managed Review
1,MBR000002,POL000002,2024-04-02,35,35-44,F,San Pedro,Metro,Lower-Middle,Employed,...,Low,Healthy Low User,0.156,0.104,0.074,0.085,Medium,Basic,Narrow,Essential
2,MBR000003,POL000003,2024-06-27,65,65+,M,Asunción,Urban,Middle,Self-Employed,...,High,Chronic Managed,0.728,0.776,0.223,0.056,Medium,Broad,Broad,Chronic Care

================================================================================
POLICIES

,policy_id,member_id,policy_start_date,policy_end_date,active_flag,plan_type,plan_tier,coverage_scope,provider_network_type,deductible_amount,...,premium_monthly,premium_annual,underwriting_load_factor,discount_factor,recommended_plan_flag,pricing_adequacy_ratio,renewal_flag,cancellation_flag,sales_channel,broker_id
0,POL000001,MBR000001,2022-09-24,2026-12-31,1,Managed Review,Mid,Full,Balanced,199.02,...,291.4,3496.8,1.139,0.092,1,0.851,1,0,Corporate,NaN
1,POL000002,MBR000002,2024-04-02,2026-12-31,1,Essential,Basic,Ambulatory,Narrow,597.15,...,198.7,2384.4,1.138,0.082,1,1.285,1,0,Direct,NaN
2,POL000003,MBR000003,2024-06-27,2026-12-31,1,Chronic Care,Premium,Full,Broad,196.63,...,430.1,5161.2,1.005,0.060,1,0.994,0,0,Direct,NaN

================================================================================
PROVIDERS

,provider_id,provider_name,provider_type,specialty_group,region,city_tier,network_status,provider_archetype,contract_type,base_cost_multiplier,diagnostic_intensity,admission_intensity,average_claim_expected,historical_volume_band,historical_suspicion_flag,provider_quality_proxy,fraud_exposure_score
0,PRV00001,Provider 1,Clinic,Pediatrics,Central,Metro,In-network,Normal,External,1.003462,Medium,Medium,209.30,High,0,High,0.177
1,PRV00002,Provider 2,Specialist Center,Pulmonology,Asunción,Semi-Urban,In-network,Normal,Standard,1.082438,Medium,Low,258.15,Low,0,Medium,0.238
2,PRV00003,Provider 3,Pharmacy,Pharmacy,Asunción,Urban,In-network,High Complexity,Standard,1.577247,Medium,Medium,319.41,Low,0,Medium,0.252

================================================================================
CLAIMS

,claim_id,member_id,policy_id,provider_id,claim_date,claim_year,claim_month,service_type,service_category,diagnosis_group,...,duplicate_claim_flag,temporal_anomaly_flag,upcoding_suspected_flag,provider_inflation_flag,mismatch_dx_proc_flag,suspicious_claim_flag,fraud_pattern_type,member_archetype_snapshot,cost_expected_band,claim_outlier_score_latent
0,CLM000000350,MBR001287,POL001287,PRV00080,2024-01-01,2024,1,Diagnostics,Laboratory,General,...,0,0,0,0,0,0,NaN,Healthy Low User,Medium,0.124
1,CLM000000547,MBR001823,POL001823,PRV00129,2024-01-01,2024,1,Diagnostics,Diagnostics,Preventive,...,0,0,0,0,0,0,NaN,Healthy Low User,Low,0.061
2,CLM000000911,MBR003002,POL003002,PRV00110,2024-01-01,2024,1,Outpatient,Follow-up Consultation,Minor Acute,...,0,0,0,0,0,0,NaN,Healthy Low User,Low,0.068

================================================================================
MEMBER_YEAR_FEATURES

,member_id,year,archetype,age,plan_type,premium_annual,claims_count_total,claims_count_outpatient,claims_count_emergency,claims_count_inpatient,...,suspicious_claim_ratio,provider_suspicious_exposure_n,acute_high_cost_event_flag,annual_cost_trend_vs_prev,loss_ratio_member,expected_cost_next_year,high_risk_flag,risk_tier,recommended_plan,pricing_gap
0,MBR000001,2024,Hyper-Utilizer / Misuse Risk,46,Managed Review,3496.8,23.0,10.0,3.0,0.0,...,0.261,1.0,0.0,NaN,1.117,3709.97,1,High,Managed Review,213.17
1,MBR000001,2025,Hyper-Utilizer / Misuse Risk,47,Managed Review,3496.8,26.0,15.0,1.0,0.0,...,0.269,0.0,0.0,0.092,1.219,4072.39,1,High,Managed Review,575.59
2,MBR000002,2024,Healthy Low User,34,Essential,2384.4,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,NaN,0.000,318.27,0,Low,Essential,-2066.13

================================================================================
PROVIDER_MONTH_FEATURES

,provider_id,year_month,claims_n,members_unique_n,billed_total,approved_total,avg_claim_amount,median_claim_amount,p95_claim_amount,emergency_claims_n,...,dx_proc_mismatch_n,high_severity_share,suspicious_claim_ratio,provider_type,specialty_group,provider_archetype,cost_vs_peer_index,utilization_density_index,anomaly_score_provider,provider_alert_level
0,PRV00001,2024-01,13,13,2742.69,2392.39,210.976154,146.86,500.6120,1,...,0,0.077,0.000,Clinic,Pediatrics,Normal,0.465,1.0,0.010,Normal
1,PRV00001,2024-02,15,15,4396.21,4124.88,293.080667,214.67,753.0730,0,...,0,0.067,0.067,Clinic,Pediatrics,Normal,0.712,1.0,0.033,Normal
2,PRV00001,2024-03,22,22,4743.86,4029.39,215.630000,174.76,432.4795,3,...,0,0.136,0.091,Clinic,Pediatrics,Normal,0.460,1.0,0.042,Normal

================================================================================
PROSPECT_SURVEY

,prospect_id,age,age_band,sex,region,dependents_n,self_rated_health,chronic_condition_flag,chronic_condition_count,recurrent_medication_flag,...,maternity_interest_flag,pharmacy_need_flag,chronic_program_interest_flag,predicted_ground_truth_archetype,risk_tier,expected_utilization_band,recommended_plan,recommended_plan_tier,notes_driver_1,notes_driver_2
0,PRS000001,30,25-34,M,Alto Paraná,1,Good,0,0,0,...,0,0,0,Family Planner,Moderate,Medium,Family Plus,Mid,Family/dependent complexity,Preference for broader network
1,PRS000002,47,45-54,F,Central,1,Good,0,0,0,...,0,0,0,Preventive User,Moderate,Low,Standard,Mid,Moderate preventive utilization,Balanced coverage preference
2,PRS000003,18,18-24,F,Asunción,1,Excellent,0,0,0,...,0,0,0,Healthy Low User,Low,Very Low,Essential,Basic,Low recent utilization,Price-sensitive coverage preference

================================================================================
DATASET_SUMMARY

               dataset   rows  columns
0  insured_members.csv   4000       32
1         policies.csv   4000       25
2           claims.csv  44144       37

In [7]:
# Missing values audit
def missing_summary(df: pd.DataFrame) -> pd.DataFrame:
    out = pd.DataFrame({
        "column": df.columns,
        "missing_n": df.isna().sum().values,
        "missing_pct": (df.isna().sum().values / len(df)).round(4)
    })
    return out.sort_values(["missing_pct", "missing_n"], ascending=[False, False]).reset_index(drop=True)

for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    display(missing_summary(df).head(15))

================================================================================
INSURED_MEMBERS

                column  missing_n  missing_pct
0        chronic_group       2852        0.713
1            member_id          0        0.000
2            policy_id          0        0.000
3            join_date          0        0.000
4                  age          0        0.000
5             age_band          0        0.000
6                  sex          0        0.000
7               region          0        0.000
8            city_tier          0        0.000
9   socioeconomic_band          0        0.000
10   employment_status          0        0.000
11      marital_status          0        0.000
12        dependents_n          0        0.000
13   family_complexity          0        0.000
14         smoker_flag          0        0.000

================================================================================
POLICIES

                     column  missing_n  missing_pct
0                 broker_id       2256        0.564
1                 policy_id          0        0.000
2                 member_id          0        0.000
3         policy_start_date          0        0.000
4           policy_end_date          0        0.000
5               active_flag          0        0.000
6                 plan_type          0        0.000
7                 plan_tier          0        0.000
8            coverage_scope          0        0.000
9     provider_network_type          0        0.000
10        deductible_amount          0        0.000
11              copay_level          0        0.000
12    annual_coverage_limit          0        0.000
13  maternity_coverage_flag          0        0.000
14   pharmacy_coverage_flag          0        0.000

================================================================================
PROVIDERS

                       column  missing_n  missing_pct
0                 provider_id          0          0.0
1               provider_name          0          0.0
2               provider_type          0          0.0
3             specialty_group          0          0.0
4                      region          0          0.0
5                   city_tier          0          0.0
6              network_status          0          0.0
7          provider_archetype          0          0.0
8               contract_type          0          0.0
9        base_cost_multiplier          0          0.0
10       diagnostic_intensity          0          0.0
11        admission_intensity          0          0.0
12     average_claim_expected          0          0.0
13     historical_volume_band          0          0.0
14  historical_suspicion_flag          0          0.0

================================================================================
CLAIMS

                  column  missing_n  missing_pct
0     fraud_pattern_type      39813       0.9019
1               claim_id          0       0.0000
2              member_id          0       0.0000
3              policy_id          0       0.0000
4            provider_id          0       0.0000
5             claim_date          0       0.0000
6             claim_year          0       0.0000
7            claim_month          0       0.0000
8           service_type          0       0.0000
9       service_category          0       0.0000
10       diagnosis_group          0       0.0000
11    diagnosis_severity          0       0.0000
12  procedure_code_group          0       0.0000
13  procedure_complexity          0       0.0000
14        emergency_flag          0       0.0000

================================================================================
MEMBER_YEAR_FEATURES

                       column  missing_n  missing_pct
0   annual_cost_trend_vs_prev       4433       0.5541
1                   member_id          0       0.0000
2                        year          0       0.0000
3                   archetype          0       0.0000
4                         age          0       0.0000
5                   plan_type          0       0.0000
6              premium_annual          0       0.0000
7          claims_count_total          0       0.0000
8     claims_count_outpatient          0       0.0000
9      claims_count_emergency          0       0.0000
10     claims_count_inpatient          0       0.0000
11      claims_count_pharmacy          0       0.0000
12         providers_unique_n          0       0.0000
13       specialties_unique_n          0       0.0000
14        preventive_claims_n          0       0.0000

================================================================================
PROVIDER_MONTH_FEATURES

                 column  missing_n  missing_pct
0           provider_id          0          0.0
1            year_month          0          0.0
2              claims_n          0          0.0
3      members_unique_n          0          0.0
4          billed_total          0          0.0
5        approved_total          0          0.0
6      avg_claim_amount          0          0.0
7   median_claim_amount          0          0.0
8      p95_claim_amount          0          0.0
9    emergency_claims_n          0          0.0
10   inpatient_claims_n          0          0.0
11  preventive_claims_n          0          0.0
12   duplicate_claims_n          0          0.0
13  suspicious_claims_n          0          0.0
14   dx_proc_mismatch_n          0          0.0

================================================================================
PROSPECT_SURVEY

                       column  missing_n  missing_pct
0                 prospect_id          0          0.0
1                         age          0          0.0
2                    age_band          0          0.0
3                         sex          0          0.0
4                      region          0          0.0
5                dependents_n          0          0.0
6           self_rated_health          0          0.0
7      chronic_condition_flag          0          0.0
8     chronic_condition_count          0          0.0
9   recurrent_medication_flag          0          0.0
10            visits_12m_band          0          0.0
11         er_visits_12m_band          0          0.0
12   hospitalization_24m_flag          0          0.0
13                smoker_flag          0          0.0
14                  bmi_group          0          0.0

================================================================================
DATASET_SUMMARY

    column  missing_n  missing_pct
0  dataset          0          0.0
1     rows          0          0.0
2  columns          0          0.0

In [8]:
# Duplicate rows audit
dup_rows = []
for name, df in datasets.items():
    dup_rows.append({
        "dataset": name,
        "duplicated_rows": int(df.duplicated().sum())
    })

pd.DataFrame(dup_rows).sort_values("duplicated_rows", ascending=False).reset_index(drop=True)

                   dataset  duplicated_rows
0          insured_members                0
1                 policies                0
2                providers                0
3                   claims                0
4     member_year_features                0
5  provider_month_features                0
6          prospect_survey                0
7          dataset_summary                0

In [9]:
# Key integrity checks
key_checks = []

# insured_members
key_checks.append({
    "dataset": "insured_members",
    "key": "member_id",
    "unique_values": members["member_id"].nunique(),
    "rows": len(members),
    "is_unique": members["member_id"].nunique() == len(members)
})
key_checks.append({
    "dataset": "insured_members",
    "key": "policy_id",
    "unique_values": members["policy_id"].nunique(),
    "rows": len(members),
    "is_unique": members["policy_id"].nunique() == len(members)
})

# policies
key_checks.append({
    "dataset": "policies",
    "key": "policy_id",
    "unique_values": policies["policy_id"].nunique(),
    "rows": len(policies),
    "is_unique": policies["policy_id"].nunique() == len(policies)
})
key_checks.append({
    "dataset": "policies",
    "key": "member_id",
    "unique_values": policies["member_id"].nunique(),
    "rows": len(policies),
    "is_unique": policies["member_id"].nunique() == len(policies)
})

# providers
key_checks.append({
    "dataset": "providers",
    "key": "provider_id",
    "unique_values": providers["provider_id"].nunique(),
    "rows": len(providers),
    "is_unique": providers["provider_id"].nunique() == len(providers)
})

pd.DataFrame(key_checks)

           dataset          key  unique_values  rows  is_unique
0  insured_members    member_id           4000  4000       True
1  insured_members    policy_id           4000  4000       True
2         policies    policy_id           4000  4000       True
3         policies    member_id           4000  4000       True
4        providers  provider_id            180   180       True

In [10]:
print("member_id overlap between members and policies:",
      set(members["member_id"]) == set(policies["member_id"]))

print("policy_id overlap between members and policies:",
      set(members["policy_id"]) == set(policies["policy_id"]))

member_id overlap between members and policies: True
policy_id overlap between members and policies: True

In [11]:
# Data types overview
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    display(df.dtypes.reset_index().rename(columns={"index": "column", 0: "dtype"}))

================================================================================
INSURED_MEMBERS

                            column    dtype
0                        member_id   object
1                        policy_id   object
2                        join_date   object
3                              age    int64
4                         age_band   object
5                              sex   object
6                           region   object
7                        city_tier   object
8               socioeconomic_band   object
9                employment_status   object
10                  marital_status   object
11                    dependents_n    int64
12               family_complexity   object
13                     smoker_flag    int64
14               alcohol_risk_flag    int64
15         physical_activity_level   object
16                       bmi_group   object
17          chronic_condition_flag    int64
18         chronic_condition_count    int64
19                   chronic_group   object
20       recurrent_medication_flag    int64
21  prior_hospitalization_24m_flag    int64
22       self_management_adherence   object
23                       archetype   object
24             baseline_risk_score  float64
25          utilization_propensity  float64
26          acute_event_propensity  float64
27      misuse_exposure_propensity  float64
28               price_sensitivity   object
29             coverage_preference   object
30              network_preference   object
31             preferred_plan_type   object

================================================================================
POLICIES

                       column    dtype
0                   policy_id   object
1                   member_id   object
2           policy_start_date   object
3             policy_end_date   object
4                 active_flag    int64
5                   plan_type   object
6                   plan_tier   object
7              coverage_scope   object
8       provider_network_type   object
9           deductible_amount  float64
10                copay_level   object
11      annual_coverage_limit    int64
12    maternity_coverage_flag    int64
13     pharmacy_coverage_flag    int64
14  chronic_care_program_flag    int64
15            premium_monthly  float64
16             premium_annual  float64
17   underwriting_load_factor  float64
18            discount_factor  float64
19      recommended_plan_flag    int64
20     pricing_adequacy_ratio  float64
21               renewal_flag    int64
22          cancellation_flag    int64
23              sales_channel   object
24                  broker_id   object

================================================================================
PROVIDERS

                       column    dtype
0                 provider_id   object
1               provider_name   object
2               provider_type   object
3             specialty_group   object
4                      region   object
5                   city_tier   object
6              network_status   object
7          provider_archetype   object
8               contract_type   object
9        base_cost_multiplier  float64
10       diagnostic_intensity   object
11        admission_intensity   object
12     average_claim_expected  float64
13     historical_volume_band   object
14  historical_suspicion_flag    int64
15     provider_quality_proxy   object
16       fraud_exposure_score  float64

================================================================================
CLAIMS

                        column    dtype
0                     claim_id   object
1                    member_id   object
2                    policy_id   object
3                  provider_id   object
4                   claim_date   object
5                   claim_year    int64
6                  claim_month    int64
7                 service_type   object
8             service_category   object
9              diagnosis_group   object
10          diagnosis_severity   object
11        procedure_code_group   object
12        procedure_complexity   object
13              emergency_flag    int64
14              inpatient_flag    int64
15                surgery_flag    int64
16               pharmacy_flag    int64
17             preventive_flag    int64
18        chronic_related_flag    int64
19      maternity_related_flag    int64
20         claim_amount_billed  float64
21       claim_amount_approved  float64
22       claim_amount_rejected  float64
23     out_of_pocket_estimated  float64
24       claim_processing_days    int64
25               approval_rate  float64
26        duplicate_claim_flag    int64
27       temporal_anomaly_flag    int64
28     upcoding_suspected_flag    int64
29     provider_inflation_flag    int64
30       mismatch_dx_proc_flag    int64
31       suspicious_claim_flag    int64
32          fraud_pattern_type   object
33   member_archetype_snapshot   object
34          cost_expected_band   object
35  claim_outlier_score_latent  float64

================================================================================
MEMBER_YEAR_FEATURES

                            column    dtype
0                        member_id   object
1                             year    int64
2                        archetype   object
3                              age    int64
4                        plan_type   object
5                   premium_annual  float64
6               claims_count_total  float64
7          claims_count_outpatient  float64
8           claims_count_emergency  float64
9           claims_count_inpatient  float64
10           claims_count_pharmacy  float64
11              providers_unique_n  float64
12            specialties_unique_n  float64
13             preventive_claims_n  float64
14                chronic_claims_n  float64
15                    billed_total  float64
16                  approved_total  float64
17                  rejected_total  float64
18                avg_claim_amount  float64
19                max_claim_amount  float64
20                p95_claim_amount  float64
21                 emergency_ratio  float64
22                 inpatient_ratio  float64
23                preventive_ratio  float64
24                   chronic_ratio  float64
25              duplicate_claims_n  float64
26             suspicious_claims_n  float64
27          suspicious_claim_ratio  float64
28  provider_suspicious_exposure_n  float64
29      acute_high_cost_event_flag  float64
30       annual_cost_trend_vs_prev  float64
31               loss_ratio_member  float64
32         expected_cost_next_year  float64
33                  high_risk_flag    int64
34                       risk_tier   object
35                recommended_plan   object
36                     pricing_gap  float64

================================================================================
PROVIDER_MONTH_FEATURES

                       column    dtype
0                 provider_id   object
1                  year_month   object
2                    claims_n    int64
3            members_unique_n    int64
4                billed_total  float64
5              approved_total  float64
6            avg_claim_amount  float64
7         median_claim_amount  float64
8            p95_claim_amount  float64
9          emergency_claims_n    int64
10         inpatient_claims_n    int64
11        preventive_claims_n    int64
12         duplicate_claims_n    int64
13        suspicious_claims_n    int64
14         dx_proc_mismatch_n    int64
15        high_severity_share  float64
16     suspicious_claim_ratio  float64
17              provider_type   object
18            specialty_group   object
19         provider_archetype   object
20         cost_vs_peer_index  float64
21  utilization_density_index  float64
22     anomaly_score_provider  float64
23       provider_alert_level   object

================================================================================
PROSPECT_SURVEY

                              column   dtype
0                        prospect_id  object
1                                age   int64
2                           age_band  object
3                                sex  object
4                             region  object
5                       dependents_n   int64
6                  self_rated_health  object
7             chronic_condition_flag   int64
8            chronic_condition_count   int64
9          recurrent_medication_flag   int64
10                   visits_12m_band  object
11                er_visits_12m_band  object
12          hospitalization_24m_flag   int64
13                       smoker_flag   int64
14                         bmi_group  object
15           physical_activity_level  object
16                preventive_mindset  object
17      price_vs_coverage_preference  object
18                   copay_tolerance  object
19                network_preference  object
20           maternity_interest_flag   int64
21                pharmacy_need_flag   int64
22     chronic_program_interest_flag   int64
23  predicted_ground_truth_archetype  object
24                         risk_tier  object
25         expected_utilization_band  object
26                  recommended_plan  object
27             recommended_plan_tier  object
28                    notes_driver_1  object
29                    notes_driver_2  object

================================================================================
DATASET_SUMMARY

    column   dtype
0  dataset  object
1     rows   int64
2  columns   int64

In [12]:
# First business sanity checks
print("insured_members age summary")
display(members["age"].describe())

print("policies premium_monthly summary")
display(policies["premium_monthly"].describe())

print("providers fraud_exposure_score summary")
display(providers["fraud_exposure_score"].describe())

insured_members age summary

count    4000.000000
mean       42.743000
std        14.264548
min        18.000000
25%        32.000000
50%        41.000000
75%        51.000000
max        80.000000
Name: age, dtype: float64

policies premium_monthly summary

count    4000.000000
mean      382.724860
std       194.615118
min       120.010000
25%       203.067500
50%       354.515000
75%       540.165000
max       897.500000
Name: premium_monthly, dtype: float64

providers fraud_exposure_score summary

count    180.000000
mean       0.280950
std        0.180704
min        0.120000
25%        0.183750
50%        0.226500
75%        0.300250
max        0.929000
Name: fraud_exposure_score, dtype: float64

In [13]:
print("insured_members age summary")
display(members["age"].describe())

print("policies premium_monthly summary")
display(policies["premium_monthly"].describe())

print("providers fraud_exposure_score summary")
display(providers["fraud_exposure_score"].describe())

insured_members age summary

count    4000.000000
mean       42.743000
std        14.264548
min        18.000000
25%        32.000000
50%        41.000000
75%        51.000000
max        80.000000
Name: age, dtype: float64

policies premium_monthly summary

count    4000.000000
mean      382.724860
std       194.615118
min       120.010000
25%       203.067500
50%       354.515000
75%       540.165000
max       897.500000
Name: premium_monthly, dtype: float64

providers fraud_exposure_score summary

count    180.000000
mean       0.280950
std        0.180704
min        0.120000
25%        0.183750
50%        0.226500
75%        0.300250
max        0.929000
Name: fraud_exposure_score, dtype: float64

In [14]:
sanity_flags = {
    "negative_ages": int((members["age"] < 0).sum()),
    "premium_monthly_non_positive": int((policies["premium_monthly"] <= 0).sum()),
    "premium_annual_non_positive": int((policies["premium_annual"] <= 0).sum()),
    "pricing_adequacy_ratio_non_positive": int((policies["pricing_adequacy_ratio"] <= 0).sum()),
    "fraud_exposure_score_outside_0_1": int(((providers["fraud_exposure_score"] < 0) | (providers["fraud_exposure_score"] > 1)).sum()),
}

pd.DataFrame(list(sanity_flags.items()), columns=["check", "n"])

                                 check  n
0                        negative_ages  0
1         premium_monthly_non_positive  0
2          premium_annual_non_positive  0
3  pricing_adequacy_ratio_non_positive  0
4     fraud_exposure_score_outside_0_1  0

In [15]:
# Audit findings
audit_findings = [
    "Core dimensions available: members, policies, providers, claims, provider-month, member-year, prospects.",
    "Members and policies appear to be structurally one-to-one at current state.",
    "Providers table looks ready for enrichment of claims and anomaly analysis.",
    "Pricing-related variables already exist in policies and can support early pricing adequacy analysis.",
    "Archetype and synthetic propensity variables in insured_members provide a strong starting point for segmentation and risk scoring.",
]

for i, finding in enumerate(audit_findings, start=1):
    print(f"{i}. {finding}")

1. Core dimensions available: members, policies, providers, claims, provider-month, member-year, prospects.
2. Members and policies appear to be structurally one-to-one at current state.
3. Providers table looks ready for enrichment of claims and anomaly analysis.
4. Pricing-related variables already exist in policies and can support early pricing adequacy analysis.
5. Archetype and synthetic propensity variables in insured_members provide a strong starting point for segmentation and risk scoring.

## Next step
Proceed to:

- define entity relationships
- map variables by module
- specify analytical base tables

in `02_data_dictionary_and_join_plan.ipynb`.